# Generated by Django 3.2.6 on 2021-09-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickledmodel',
            name='args',
            field=models.CharField(default=None, max_length=250, null=True),
        ),
    ]
