# Generated by Django 3.2.6 on 2021-09-02 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizers', '0002_pickledmodel_args'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickledmodel',
            name='args',
            field=models.TextField(default=None, max_length=500, null=True),
        ),
    ]
