# Generated by Django 3.2.6 on 2021-09-02 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizers', '0003_alter_pickledmodel_args'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickledmodel',
            name='args',
        ),
    ]
