# Generated by Django 3.2.6 on 2021-09-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizers', '0004_remove_pickledmodel_args'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickledmodel',
            name='args',
            field=models.CharField(default=None, max_length=100, null=True),
        ),
    ]
