# Generated by Django 3.2.6 on 2021-09-07 18:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizers', '0006_auto_20210907_1053'),
    ]

    operations = [
        migrations.DeleteModel(
            name='summarize_input',
        ),
        migrations.DeleteModel(
            name='summary_output',
        ),
    ]
