# Generated by Django 3.2.6 on 2021-09-07 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizers', '0007_auto_20210907_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickledmodel',
            name='purpose',
            field=models.CharField(choices=[('Preprocessor', 'Preprocessor'), ('Summarizer', 'Summarizer')], max_length=100),
        ),
    ]
