# Generated by Django 3.2.6 on 2021-09-07 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Summarizers', '0008_alter_pickledmodel_purpose'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pickledmodel',
            name='args',
        ),
        migrations.AlterField(
            model_name='pickledmodel',
            name='accuracy',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=10),
        ),
    ]
