# Generated by Django 3.2.6 on 2021-08-09 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process_type', models.CharField(choices=[('Book', 'Book summarize'), ('Keyword', 'Keyword based summarize'), ('correct PDF', 'PDF normalize')], max_length=50)),
                ('file', models.FileField(upload_to='processes/')),
                ('progress', models.CharField(choices=[('start', 'start'), ('extract', 'extract'), ('get_text', 'get_text'), ('summary', 'summary'), ('finished', 'finished'), ('unfinished', 'unfinished'), ('error', 'error')], max_length=30)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
